### ISSUE TITLE
Error while running  python main.py --video videos\video.avi

### ISSUE THREAD

**Issue by ayanasser** [stevenzchen/pose-trainer#1]
the openpose demo worked correctly for me for webcam , 
but when i turned to this repo it gave me this error when i run this on any video 
where in the paper or this one video.avi

`$ python main.py --video videos\video.avi
Starting pose estimation demo.

Error:
VideoCapture (IP camera/video) could not be opened for path: '..\videosvideo.avi'. If it is a video path, is the path correct?

Coming from:
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():37
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():41
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():203
C:\Users\BioHelwan\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\BioHelwan\Anaconda3\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
processing video file...
Exercise arm detected as: left.
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    main()
  File "main.py", line 53, in main
    (correct, feedback) = evaluate_pose(pose_seq, args.exercise)
  File "D:\Got\after first discussion\Main\pose-trainer-master\evaluate.py", line 18, in evaluate_pose
    return _bicep_curl(pose_seq)
  File "D:\Got\after first discussion\Main\pose-trainer-master\evaluate.py", line 55, in _bicep_curl
    upper_arm_vecs = upper_arm_vecs / np.expand_dims(np.linalg.norm(upper_arm_vecs, axis=1), axis=1)
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 2287, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
`

**Comment by ayanasser** [comment]
`$ python main.py --video videos\video.avi
Starting pose estimation demo.

Error:
VideoCapture (IP camera/video) could not be opened for path: '..\videosvideo.avi'. If it is a video path, is the path correct?

Coming from:
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():37
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\producer\videoCaptureReader.cpp:op::VideoCaptureReader::VideoCaptureReader():41
- D:\Users\Gines\Desktop\openpose-master\openpose-1.3.0\src\openpose\utilities\flagsToOpenPose.cpp:op::flagsToProducer():203
C:\Users\BioHelwan\Anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
C:\Users\BioHelwan\Anaconda3\lib\site-packages\numpy\core\_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
processing video file...
Exercise arm detected as: left.
Traceback (most recent call last):
  File "main.py", line 84, in <module>
    main()
  File "main.py", line 53, in main
    (correct, feedback) = evaluate_pose(pose_seq, args.exercise)
  File "D:\Got\after first discussion\Main\pose-trainer-master\evaluate.py", line 18, in evaluate_pose
    return _bicep_curl(pose_seq)
  File "D:\Got\after first discussion\Main\pose-trainer-master\evaluate.py", line 55, in _bicep_curl
    upper_arm_vecs = upper_arm_vecs / np.expand_dims(np.linalg.norm(upper_arm_vecs, axis=1), axis=1)
  File "C:\Users\BioHelwan\Anaconda3\lib\site-packages\numpy\linalg\linalg.py", line 2287, in norm
    return sqrt(add.reduce(s, axis=axis, keepdims=keepdims))
numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1
`

**Comment by stevenzchen** [comment]
Hi Aya, did you already figure this out? I think you would need to try double slashes \\, or try specifying the full file path.

**Comment by ayanasser** [comment]
Hi steven , thank you 
it's worked for me  when i use double slashes or forward slash

**Comment by eng100200** [comment]
@ayanasser hello, my question is whether it requires two videos, one for video model video to which we want comaprison or matching, and then one for testing? is it?

**Comment by stevenzchen** [comment]
Only one video is needed for evaluation. Please read the paper and the source code for more information.
