### ISSUE TITLE
is there a do ? it works for mac ?

### ISSUE THREAD

**Issue by sgu-fai** [stevenzchen/pose-trainer#3]
I took a quick look at the code of main.py, I was wondering how it can work with mac with this line:

`openpose_path = os.path.join('bin', 'OpenPoseDemo.exe')`

**Comment by sgu-fai** [comment]
an example ? quick start ?

**Comment by sgu-fai** [comment]
the option write_keypoint_json of openpose has changed so pose-trainer is not working anymore

**Comment by stevenzchen** [comment]
This repo is not maintained, so it's not expected to function. It was only made to work on Windows since OpenPose has a Windows executable, although it could be modified to run on a different platform.

The updated README notes this now.
