### ISSUE TITLE
Help needed in understanding how median filters help in removing noisy keypoints

### ISSUE THREAD

**Issue by iam-Shashank** [stevenzchen/pose-trainer#4]
Hey, great paper! So, we were making something similar like pose-trainer. I had 2 questions regarding the noise removal, use of median filter: 
1. It's mentioned in the paper: "When OpenPose generates noise keypoints...". Could you give an example of what would be considered as noisy keypoints? Like are you referring to the jitter when one plays a video output with all the keypoints? Is that what median filter is trying to smooth out?
![image](https://user-images.githubusercontent.com/34963991/97081229-8fa95000-161e-11eb-83a9-eb4c98107785.png)

2. Also in the [code](https://github.com/stevenzchen/pose-trainer/blob/master/DTW-BicepCurl.ipynb), you're applying medfilter to the array of calculated angles. Now, I am aware of how applying image filters to keypoints or to mages in general helps reduce noise as it's easy to see the output, but a bit difficult to get what kind of output changes are happening here when they are applied to angles.
What would be the difference if the filter was applied to the keypoint sequence directly before calculating the angles? It would be really helpful if you could give an explanation/ point me to some reading material on how applying filter to angles gives certain output changes (like when they're applied to keypoints, they reduce jitter in the x,y coordinates, so when they're applied to angles, are they reducing the jitter in angle values and making them more continuous??)
![image](https://user-images.githubusercontent.com/34963991/97111486-03be2380-1705-11eb-861a-1e38e96bf7ac.png)
![image](https://user-images.githubusercontent.com/34963991/97111503-19cbe400-1705-11eb-8a00-dcf4fc07fa40.png)

Sorry for the long question, just wanted to have a good understanding/intuition before using the method described in your paper. Thanks! great work!

**Comment by stevenzchen** [comment]
Hi Shashank, this work is over two years old, and I can’t say I remember the details on this. OpenPose doesn’t produce smooth predictions over time, and the median filter just smooths out the angles as you said. I’d encourage you to experiment yourself if you want to know more, I don’t really have more to tell you. 

Just a warning that this repo is no longer maintained and compatible with OpenPose, so I’d suggest writing your own codebase or finding a more modern project: this one will need modifications to work.

**Comment by iam-Shashank** [comment]
Thanks Steven! yeah we are not using this repo codebase directly or OpenPose in our project. We basically referred to the research paper and the code for the DTW part.  Your research paper was quite helpful👍
